---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
    register: result
  
  - name: Add host group
    add_host:
      name: "{{ item.id }}"
      group: osp_instance_id_group
    with_items: "{{result.openstack_servers}}"

  - debug: var=groups

  - debug: msg="{{ item }}"
    with_items: "{{ groups.osp_instance_id_group }}"

  - name: Delete instances
    os_server:
      name: "{{ item }}"
      state: absent
    with_items: "{{ groups.osp_instance_id_group }}"