---
- name: Deploy 3 tier app on AWS
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Gather Facts from aws
    ec2_instance_facts:
      region: us-east-1
      filters:
        "tag:owner": xujin@redhat.com
    register: ec2_instances

  - name: Create In Memory Inventory
    add_host:
       group: "{{item.0}}"
       hostname: "{{item.2}}"
       ansible_host: "{{item.1}}"
    with_together:
      - "{{ ec2_instances.instances | map(attribute='tags.AnsibleGroup')| list }}"
      - "{{ ec2_instances.instances | map(attribute='public_ip_address')| list }}"
      - "{{ ec2_instances.instances | map(attribute='tags.Name')| list }}"

  - name: Create apps group
    add_host: hostname="{{ item }}" groups=apps
    with_items: "{{ groups.tag_AnsibleGroup_apps }}"

  - name: Create frontend group
    add_host: hostname="{{ item }}" groups=frontend
    with_items: "{{ groups.tag_AnsibleGroup_frontends }}"

  - name: Create db group
    add_host: hostname="{{ item }}" groups=db
    with_items: "{{ groups.tag_AnsibleGroup_appdbs }}"

# - name: Test play against In-memory inventory
#   hosts: apps frontend db
#   gather_facts: false
#   tasks:
#     - ping:

- name: Setup Repos
  hosts: apps:frontend:db
  gather_facts: false
  become: true
  tags:
    - common

  tasks:
    - name: Copy repo file
      copy:
        src: ../files/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo
 
- import_playbook: provision_database_tier.yml
- import_playbook: provision_app_tier.yml
- import_playbook: provision_load_balancer_tier.yml

...