- hosts: localhost
  gather_facts: false
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    TOWER_GUID: "{{ lookup('env','TOWER_GUID') }}"
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}
      group: workstation
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
 
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: 'frontend1'
    register: openstack_info
  
  - name: Check if all osp instance exist
    debug: "{{ openstack_info.openstack_servers | length }}"
    register: osp_instance

#  - debug: var=osp_instance

  - name: Access website for QA
    uri:
      url: "http://{{ item.public_v4 }}/ping"
      status_code: 200
      return_content: yes
    when: 'item.hostname == "frontend1"'
    loop: "{{ openstack_info.openstack_servers }}"
    register: qa_webpage
    ignore_errors: yes

  - debug: var=qa_webpage

  - name: Fail
    fail:
    when: "'alive' not in qa_webpage.results[0].content" 

  
- hosts: localhost
  gather_facts: false
  tasks: 
  - name: Run tower-cli command
    command: |
      tower-cli host list --group tag_AnsibleGroup_frontends -f json
    register: tower_host_info

  - set_fact:
      tower_host_vars: "{{ tower_host_info.stdout | from_json }}"

  - debug: 
      msg: "{{ tower_host_vars.results[0].name }}"

  - name: Access website for PROD
    uri:
      url: "http://{{ tower_host_vars.results[0].name }}/ping"
      status_code: 200
      return_content: yes
    register: prod_webpage

  - debug: var=prod_webpage

  - name: Fail
    fail:
    when: "'alive' not in prod_webpage.content" 

  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"


