- name: Get database IP address with hostvars for app servers
  hosts: db
  gather_facts: true
  tags:
    - application_servers

  tasks: []

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: apps
  become: true
  gather_facts: true
  tags:
    - application_servers

  roles:

    - flask
