---
- name: Deploy 3 tier app on AWS
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Refresh inventory to ensure new instances exist in inventory
    meta: refresh_inventory

  - name: Create frontend group
    add_host: hostname="{{ item }}" groups=frontend
    with_items: "{{ groups.tag_AnsibleGroup_frontends }}"

- hosts: frontend
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://{{ groups.frontend[0] }}/ping"
      return_content: yes
    until: '"alive" in result.content'
    retries: 10
    delay: 1
    register: result
    delegate_to: localhost

  # - name: Curl website
  #   uri:
  #     url: "http://localhost"
  #     return_content: yes
  #     status_code: 200
  #   register: webpage
        
  # - debug: var=webpage.content

  # - name: Fail if 'Ansible has done its job' is not in the page content
  #   fail:
  #   when: "'Ansible has done its job' not in webpage.content"